### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Hshshahshsh** [jmesfo0/RobloxScripts#1]
The gui is not showing up

**Comment by jmesfo0** [comment]
![RobloxScreenShot20221202_021307030](https://user-images.githubusercontent.com/42681518/205269484-266ba2f6-2ba4-49f7-a551-3a2f5690128f.png)

**Comment by Hshshahshsh** [comment]
> ![RobloxScreenShot20221202_021307030](https://user-images.githubusercontent.com/42681518/205269484-266ba2f6-2ba4-49f7-a551-3a2f5690128f.png)

It doesn't work for me yesterday it works but now it's not working

**Comment by outgaze** [comment]
@jmesfo0 can vouch this is still happening and currently not openning for me.

**Comment by Shadwbtw** [comment]
it doesnt work for me either. please do something. thanks.

**Comment by jmesfo0** [comment]
> it doesnt work for me either. please do something. thanks.



> @jmesfo0 can vouch this is still happening and currently not openning for me.


it is fixed now guys sorry, i had put synapse only commands in the script `if type(v) == "function" and islclosure(v) and not is_synapse_function(v) then`
